name: Daily Github-Trending

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run: |
        python scraper.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git status
          if git status --porcelain | grep -q '^?? \|^A  \|^M  '; then
            echo "Changes detected, committing..."
            git commit -m "Update"
            git push
          else
            echo "No changes to commit"
          fi 
